### ISSUE TITLE
add lambda-github-runner to comparison chart

### ISSUE THREAD

**Issue by fgregg** [jonico/awesome-runners#13]
Hi y'all!

Thanks for this great resource. I'd love to see how [lambda-github-runner](https://github.com/nwestfall/lambda-github-runner) stacks up!

**Comment by jonico** [comment]
Hi @fgregg, thanks for pointing to that solution, maybe the maintainer (or you) are interested in creating a PR here 😊

**Comment by fgregg** [comment]
it's quite cool in concept, but the docs were incomplete in getting it set up. and once i did get it set up, my github action workflows didn't really work (various hacks need to be put in place to deal with the fact that within a lambda container you can only write to /tmp)

not an actively developed project right now, so can probably pass.

**Comment by jonico** [comment]
thank you for testing!
